# -*- coding: utf-8 -*-
"""SparseSolvers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrC5InhJ1asyOiXcBbHvvzKUknQvFrXE
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

n = 50
sparseMat1 = np.zeros([n,n]); sparseMat2 = np.zeros([n,n])
sparseMat1[0,:] = 1; sparseMat1[:,0] = 1;
sparseMat2[-1,:]  = 1; sparseMat2[:,-1] = 1;
for i in range(n):
  sparseMat1[i,i] = 1
  sparseMat2[i,i] = 1

plt.spy(sparseMat1)
plt.show()

p,l,u = la.lu(sparseMat1)

fig, axs = plt.subplots(1,3)
axs[0].spy(p,markersize=2)
axs[1].spy(l,markersize=2)
axs[2].spy(u,markersize=2)
for ax in axs.flat:
  ax.set(xticks=([]),yticks=([]))
plt.savefig('Q2-2c.png',dpi=500,pad_inches=0.01)

plt.spy(sparseMat2)
plt.show()

p,l,u = la.lu(sparseMat2)

fig, axs = plt.subplots(1,3)
axs[0].spy(p,markersize=2,color='green')
axs[1].spy(l,markersize=2,color='green')
axs[2].spy(u,markersize=2,color='green')
for ax in axs.flat:
  ax.set(xticks=([]),yticks=([]))
plt.savefig('Q2-2d.png',dpi=500,pad_inches=0.01)

plt.spy(sparseMat1,markersize=5)
plt.savefig('Q2-2a.png',dpi=500,pad_inches=0.01)
plt.clf()
plt.spy(sparseMat2,markersize=5,color='green')
plt.savefig('Q2-2b.png',dpi=500,pad_inches=0.01)